# Generated by Django 2.2.9 on 2020-03-11 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emp_goal_data_man',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=50)),
                ('goal_id', models.CharField(max_length=100)),
                ('goal_title', models.CharField(max_length=100)),
                ('goal_description', models.CharField(max_length=100)),
                ('due_date', models.CharField(default='NA', max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Emp_goal_feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=50)),
                ('goal_id', models.CharField(max_length=100)),
                ('employee_comment', models.CharField(default='NA', max_length=100)),
                ('employee_ratings', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='EmpData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=50)),
                ('job_title', models.CharField(default='NA', max_length=25)),
                ('last_ap_date', models.CharField(max_length=100)),
                ('reporting_mail', models.EmailField(max_length=50)),
                ('doj', models.CharField(max_length=100)),
                ('evalute_by', models.CharField(max_length=100)),
                ('dept', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Manager_goal_feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=50)),
                ('goal_id', models.CharField(max_length=100)),
                ('manager_comment', models.CharField(default='NA', max_length=100)),
                ('manager_ratings', models.IntegerField(default=0)),
            ],
        ),
    ]
