# Generated by Django 2.2.9 on 2020-03-13 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miss_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Managers_associations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=50)),
                ('dept', models.CharField(max_length=50)),
            ],
        ),
    ]
