# Generated by Django 2.2.9 on 2020-03-14 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miss_management', '0003_team_goal_data_man'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Team_goal_data_man',
        ),
    ]
